-- SQL Table Structure for System Usage Tracking
-- This table tracks which systems are currently in use by students and staff
-- The table is automatically created when update_usage.php is first called
--
-- IMPORTANT: System ID and IP Address are tracked separately:
-- - system_id: Unique ID generated by JavaScript (SYS-ABCD1234) - per computer/browser
-- - ip_address: Network IP address (192.168.1.100) - can be same for multiple computers on same network

CREATE TABLE IF NOT EXISTS system_usage (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    username VARCHAR(100),
    role ENUM('student','staff') NOT NULL,
    system_id VARCHAR(50),
    ip_address VARCHAR(45),
    last_active DATETIME NOT NULL,
    status ENUM('active','inactive') DEFAULT 'active',
    INDEX idx_user_id (user_id),
    INDEX idx_system_id (system_id),
    INDEX idx_ip_address (ip_address),
    INDEX idx_status (status),
    INDEX idx_last_active (last_active)
);

-- Optional: Add foreign key constraint (if users table exists)
-- ALTER TABLE system_usage 
-- ADD CONSTRAINT fk_system_usage_user 
-- FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- Example queries:
-- View all active systems:
-- SELECT * FROM system_usage WHERE status = 'active' ORDER BY last_active DESC;

-- View systems inactive for more than 10 minutes:
-- SELECT * FROM system_usage WHERE status = 'active' AND last_active < DATE_SUB(NOW(), INTERVAL 10 MINUTE);

-- Clean up old inactive records (older than 7 days):
-- DELETE FROM system_usage WHERE status = 'inactive' AND last_active < DATE_SUB(NOW(), INTERVAL 7 DAY);

