<?php
/**
 * System Usage Tracking Backend
 * Handles login, heartbeat, and logout actions from student and staff dashboards
 */

session_start();

// Check if user is logged in
if (!isset($_SESSION['user_id']) || !isset($_SESSION['role'])) {
    http_response_code(401);
    echo json_encode(['success' => false, 'message' => 'Unauthorized']);
    exit();
}

// Database configuration
$db_host = 'localhost';
$db_user = 'root';
$db_pass = '';
$db_name = 'LARS';

$conn = new mysqli($db_host, $db_user, $db_pass, $db_name);
if ($conn->connect_error) {
    http_response_code(500);
    echo json_encode(['success' => false, 'message' => 'Database connection failed']);
    exit();
}

// Get action from POST request
$action = $_POST['action'] ?? '';

// Get user information from session
$user_id = $_SESSION['user_id'];
$role = $_SESSION['role'];
$username = $_SESSION['username'] ?? $_SESSION['admission_number'] ?? $_SESSION['name'] ?? '';

// Get system_id and ip_address from POST
$system_id = $_POST['system_id'] ?? '';
$ip_address = $_SERVER['REMOTE_ADDR'] ?? '';

// Validate action
if (!in_array($action, ['login', 'heartbeat', 'logout'])) {
    http_response_code(400);
    echo json_encode(['success' => false, 'message' => 'Invalid action']);
    exit();
}

// Ensure system_usage table exists
// Note: System ID and IP Address are tracked separately:
// - system_id: Unique ID generated by JavaScript (SYS-ABCD1234) - per computer/browser
// - ip_address: Network IP address (192.168.1.100) - can be same for multiple computers on same network
$create_table = "CREATE TABLE IF NOT EXISTS system_usage (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    username VARCHAR(100),
    role ENUM('student','staff') NOT NULL,
    system_id VARCHAR(50),
    ip_address VARCHAR(45),
    last_active DATETIME NOT NULL,
    status ENUM('active','inactive') DEFAULT 'active',
    INDEX idx_user_id (user_id),
    INDEX idx_system_id (system_id),
    INDEX idx_ip_address (ip_address),
    INDEX idx_status (status),
    INDEX idx_last_active (last_active)
)";

$conn->query($create_table);

// Get username from database if not in session
if (empty($username)) {
    $stmt = $conn->prepare("SELECT username, name, admission_number FROM users WHERE id = ?");
    $stmt->bind_param("i", $user_id);
    $stmt->execute();
    $result = $stmt->get_result();
    if ($result->num_rows > 0) {
        $user_data = $result->fetch_assoc();
        // Prefer username, then admission_number, then name
        $username = $user_data['username'] ?? $user_data['admission_number'] ?? $user_data['name'] ?? 'User-' . $user_id;
    } else {
        $username = 'User-' . $user_id;
    }
    $stmt->close();
}

$current_time = date('Y-m-d H:i:s');
$response = ['success' => false, 'message' => ''];

// Handle different actions
switch ($action) {
    case 'login':
        // Insert or update system usage record on login
        // Check if record exists for this user
        $stmt = $conn->prepare("SELECT id FROM system_usage WHERE user_id = ?");
        $stmt->bind_param("i", $user_id);
        $stmt->execute();
        $result = $stmt->get_result();
        
        if ($result->num_rows > 0) {
            // Update existing record
            $stmt->close();
            $stmt = $conn->prepare("UPDATE system_usage SET 
                username = ?, 
                role = ?, 
                system_id = ?, 
                ip_address = ?, 
                last_active = ?, 
                status = 'active' 
                WHERE user_id = ?");
            $stmt->bind_param("sssssi", $username, $role, $system_id, $ip_address, $current_time, $user_id);
        } else {
            // Insert new record
            $stmt->close();
            $stmt = $conn->prepare("INSERT INTO system_usage 
                (user_id, username, role, system_id, ip_address, last_active, status) 
                VALUES (?, ?, ?, ?, ?, ?, 'active')");
            $stmt->bind_param("isssss", $user_id, $username, $role, $system_id, $ip_address, $current_time);
        }
        
        if ($stmt->execute()) {
            $response = ['success' => true, 'message' => 'Login tracked successfully'];
        } else {
            $response = ['success' => false, 'message' => 'Failed to track login: ' . $conn->error];
        }
        $stmt->close();
        break;
        
    case 'heartbeat':
        // Update last_active timestamp every 60 seconds
        $stmt = $conn->prepare("UPDATE system_usage SET 
            last_active = ?, 
            status = 'active' 
            WHERE user_id = ?");
        $stmt->bind_param("si", $current_time, $user_id);
        
        if ($stmt->execute()) {
            $response = ['success' => true, 'message' => 'Heartbeat updated'];
        } else {
            $response = ['success' => false, 'message' => 'Failed to update heartbeat'];
        }
        $stmt->close();
        break;
        
    case 'logout':
        // Set status to inactive on logout
        $stmt = $conn->prepare("UPDATE system_usage SET 
            status = 'inactive', 
            last_active = ? 
            WHERE user_id = ?");
        $stmt->bind_param("si", $current_time, $user_id);
        
        if ($stmt->execute()) {
            $response = ['success' => true, 'message' => 'Logout tracked successfully'];
        } else {
            $response = ['success' => false, 'message' => 'Failed to track logout'];
        }
        $stmt->close();
        break;
}

// Also mark records as inactive if last_active is more than 2 minutes old (safety check)
// Heartbeat runs every 60 seconds, so 2 minutes gives buffer for network delays
$conn->query("UPDATE system_usage SET status = 'inactive' 
    WHERE status = 'active' 
    AND last_active < DATE_SUB(NOW(), INTERVAL 2 MINUTE)");

$conn->close();

// Return JSON response
header('Content-Type: application/json');
echo json_encode($response);

